language: node_js
node_js:
  - "iojs"
  - 4
  - 6
  - 7
addons:
  code_climate:
    repo_token: f12a82bf7dcafaee8297e2ccdc611cf67768526062840a62c5de775fd6ac3f0f
after_success:
  - npm install -g codeclimate-test-reporter codecov
  - codeclimate-test-reporter < lcov.info
  - codecov
